### ISSUE TITLE
FR: Support for ARM64

### ISSUE THREAD

**Issue by lindermayr** [mpdcampbell/traefik-geoip-filter#42]
Most of my Docker containers run on Raspberry Pi or in a free instance of Oracle Cloud. Unfortunately, they only support ARM64, so your software always exits with this error: exec /docker-entrypoint.sh: exec format error

I've found some instructions for adding multiple platform support, but in lack of programming skills, I cant do it on my own:
https://docs.docker.com/build/building/multi-platform/

Do you think it'd be possible to tweak your software to play nice with different architectures like ARM64? That'd be a huge help!

**Comment by mpdcampbell** [comment]
So fair warning, I haven't tested this at all. But I pushed some ARM builds under the edge tag.
In [this line](https://github.com/mpdcampbell/traefik-geoip-filter/blob/92ddfc9016451780ca9a438a562d778d4a1ce778/docker-compose.example.yml#L19) of the docker compose add the edge tag to pull the right image, then run the container as normal.
`      image: mpdcampbell/traefik-geoip-filter:edge`

Let me know if works or not, when I have more time I'll test it on a Raspberry Pi.
